# Generated by Django 2.2.16 on 2020-09-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200923_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='botId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
