# Generated by Django 2.2.16 on 2020-09-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
