# Generated by Django 2.2.16 on 2020-09-22 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eng', models.CharField(max_length=200)),
                ('kor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wordbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=200)),
                ('kor', models.CharField(max_length=200)),
                ('wordbook_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='word.Wordbook')),
            ],
        ),
    ]
